#! /usr/bin/python
# D:{SADASANT;}
import euler
def euler0029(nS,nE): # nS must be 2 and nE must be 100 in order to solve the problem
  """ How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100? """
  R = []
  for a in xrange(nS,nE+1):
    for b in xrange(nS,nE+1):
      r = a**b
      print r
      R.append(r)
  return 'the answer is ',len(list(set(R)))

print euler0029(2,100)
